### ISSUE TITLE
Improve Button Design : React - TailwindCSS 

### ISSUE THREAD

**Issue by miikkuu** [miikkuu/blogify#7]
Currently the buttons are not Responsive across devices and also not organised properly.
This design can be improved.

**Comment by m1her** [comment]
I'm interested, could you add more details please ?
Thank you,

**Comment by malik-na** [comment]
Hi @miikkuu !

I can fix this. Please assign it to me.

**Comment by miikkuu** [comment]
@m1her go ahead!

**Comment by m1her** [comment]
i will leave it to @malik-na 
thank you though

**Comment by miikkuu** [comment]
@malik-na please proceed.

**Comment by miikkuu** [comment]
Let me know if you need any help @malik-na

**Comment by malik-na** [comment]
Hi!
Did you want this to be fixed?

<img width="1440" alt="Screenshot 2024-07-22 at 7 51 59 PM" src="https://github.com/user-attachments/assets/158dcc1f-d6a0-4ec8-8d42-ea24e2f9866e">

I fixed it here: 


<img width="1438" alt="Screenshot 2024-07-22 at 7 56 11 PM" src="https://github.com/user-attachments/assets/25961280-a0e1-46e2-ab38-ad4b859413a5">

I fixed the same on register page as well.

Please accept the PR and let me know if there are additional changes to be made.

**Comment by miikkuu** [comment]
@malik-na Ok, it works , I am going to accept the PR.
Thank You for Contributing !
You can now Star ⭐ the Blogify project, if haven't done already.
