### ISSUE TITLE
Add Delete Comment Functionality - Node , React

### ISSUE THREAD

**Issue by miikkuu** [miikkuu/blogify#9]
Add ability to delete comments

**Comment by iamworrell** [comment]
Can you assign this to me?

**Comment by malik-na** [comment]
Hi!

I can fix this, please assign it to me.

**Comment by miikkuu** [comment]
@malik-na Sure!

**Comment by miikkuu** [comment]
@malik-na  If you are not comfortable in backend , you can just do the Frontend part of this issue (creating an appropriate ,responsive delete button for comments ), and can keep a placeholder api link.
I will do the backend.
Or , if you feel confident  , go ahead with backend too.
It will be a Great Frontend + Backend Contribution.

In any case let me know if you are still  working on it or not or if you need some help.
Thanks

**Comment by malik-na** [comment]
Hey! I'll be working on it tonight. You're right, I'm not sure about backend but I'll try. Or else I'll just set it up on the frontend.

**Comment by miikkuu** [comment]
@malik-na any update?

**Comment by malik-na** [comment]
Hi. No, I couldn't start the backend. Without that I cannot make or access existing posts or comments.

**Comment by miikkuu** [comment]
@malik-na I have updated the Backend, so now you can start it without using AWS ,
If you don't have it.
PS: Mongo Cluster is still important though.

Just make a free Mongo cluster on MongoAtlas and save the URi in env.

The backend should work.

**Comment by miikkuu** [comment]
@malik-na any update? You need help?
